### ISSUE TITLE
how to start it

### ISSUE THREAD

**Issue by brealisty** [foolwood/DaSiamRPN#5]
after changing the path to code folder and downloading the model file, when run the tracker_SiamRPN.m, get error:
`Undefined function or variable 'generate_python_command'.`

so, how to change the command. plz

**Comment by foolwood** [comment]
This repository includes PyTorch code for reproducing the results on **VOT2018**.
So you should use [VOT toolkit](https://github.com/votchallenge/vot-toolkit).

```
git clone https://github.com/votchallenge/vot-toolkit.git
cd vot-toolkit && mkdir vot2018 && cd vot2018
git clone https://github.com/foolwood/DaSiamRPN.git
/user/local/MATLAB/R2016b/bin/matlab -nodisplay
>> run ../toolkit_path
>> workspace_create
>> 7
>> SiamRPN
>> 2
```

Follow this [instructions](https://github.com/foolwood/DaSiamRPN/blob/master/README.md#detailed-steps-to-install-the-prerequisites) to configure tracker_SiamRPN.m. After that, you can run the following command in MATLAB command line.
```
>> run_experiments
```

For more detailed information on vot-toolkit, please see [this tutorial](http://www.votchallenge.net/howto/workspace.html).

**Comment by BestSonny** [comment]
@foolwood  I followed your instructions and got the error
```python 
Initializing` workspace ...
Checking for toolkit updates on GitHub.
Verifying native components ...
Testing TraX protocol support for tracker SiamRPN.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
Error using tracker_load (line 127)
Tracker has not passed the TraX support test.

Error in run_experiments (line 8)
tracker = tracker_load('SiamRPN');
```

Any hints? Thank you.

**Comment by foolwood** [comment]
@BestSonny 
This problem is issued by [#7082](https://github.com/pytorch/pytorch/issues/7082).
Please use **PyTorch 0.3.1**.

**Comment by Lauretta1995** [comment]
@BestSonny 
Do you solve the problem? I get the same problem, pytorch version is 0.4.0.

**Comment by BestSonny** [comment]
@Lauretta1995  downgrade to PyTorch 0.3.1.

**Comment by Lauretta1995** [comment]
PyTorch version is 0.3.1, but the problem(TraX support not detected) still exists. Do you have this problem?

**Comment by Lauretta1995** [comment]
@BestSonny   PyTorch version is 0.3.1, but the problem(TraX support not detected) still exists. Do you have this problem?

**Comment by Lauretta1995** [comment]
@BestSonny  The problem is already solved!

**Comment by BestSonny** [comment]
@Lauretta1995  How did you fix it? Thank you.

**Comment by Lauretta1995** [comment]
@BestSonny yes, there is  no other way.

**Comment by Cris-zj** [comment]
Downgrade is not work for me, so I change the Specify timeout period in tracker_run.m following [this](https://blog.csdn.net/aiqiu_gogogo/article/details/79454997) 图片: https://images-cdn.shimo.im/rehvINns0oUSQmnY/image.png
and maybe it influence the speed. I get slow fps.

**Comment by SuTanTank** [comment]
I did use 0.3.1 and the Testing Trex step still failed with 30s timeout triggered. Change the timeout just results in longer wait before the error info pop out.

**Comment by BagusYusuf** [comment]
hi, do you solve this problem ???
i am using 0.3.1 and still have same issue

**Comment by brealisty** [comment]
@BagusYusuf   do as what foolwood answered. so you need to konw about the [VOT toolkit](https://github.com/votchallenge/vot-toolkit)

**Comment by zzpustc** [comment]
Is there any problem to use conda to install? @foolwood @brealisty

**Comment by foolwood** [comment]
@zzpustc 

You can run with conda without any program crash.
The only problem is 
`If you use Conda to install the PyTorch and OpenCV. The results may not be guaranteed. (good or bad?)`

**Comment by zkloveai** [comment]
按照你的上述方法。出现了问题。
警告: 在路径中未找到 "D:\vot-toolkit-master\native"。 
> In rmpath (line 57)
  In workspace_create (line 142) 
Downloading TraX source from "https://codeload.github.com/votchallenge/trax/zip/master". Please wait ...
Unable to unpack TraX source code.
错误使用 initialize_native (line 16)
Unable to compile native resources.

出错 workspace_create (line 143)
initialize_native();

**Comment by najingligong1111** [comment]
警告: 在路径中未找到 "/home/lei/DaSiamRPN/vot-toolkit/native"。 
> In rmpath (line 66)
  In workspace_create (line 142) 
Downloading TraX source from "https://codeload.github.com/votchallenge/trax/zip/master". Please wait ...
Unable to unpack TraX source code.
错误使用 initialize_native (line 16)
Unable to compile native resources.

出错 workspace_create (line 143)
initialize_native();

**Comment by BagusYusuf** [comment]
hi, I try to start your tracker stand-alone (vot_SiamRPN.py), and after creating vot class, it missing image.txt 
is there any file that I need to add?
thanks in advance.

**Comment by najingligong1111** [comment]
>> run_test
Initializing workspace ...
Verifying native components ...
Loading sequences ...
Testing TraX protocol support for tracker SiamRPN.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
错误使用 tracker_load (line 127)
Tracker has not passed the TraX support test.

出错 run_test (line 8)
tracker = tracker_load('SiamRPN');
使用了0.3.1

**Comment by najingligong1111** [comment]
Initializing workspace ...
Verifying native components ...
Loading sequences ...
Testing TraX protocol support for tracker SiamRPN.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
错误使用 tracker_load (line 127)
Tracker has not passed the TraX support test.

出错 run_test (line 8)
tracker = tracker_load('SiamRPN');


pytorch 0.3.1   matlab2016b

**Comment by najingligong1111** [comment]
> hi, do you solve this problem ???
> i am using 0.3.1 and still have same issue

have you solve it?

**Comment by najingligong1111** [comment]
> @foolwood I followed your instructions and got the error
> 
> ```python
> Initializing` workspace ...
> Checking for toolkit updates on GitHub.
> Verifying native components ...
> Testing TraX protocol support for tracker SiamRPN.
> Tracker execution interrupted: Unable to establish connection.
> TraX support not detected.
> Error using tracker_load (line 127)
> Tracker has not passed the TraX support test.
> 
> Error in run_experiments (line 8)
> tracker = tracker_load('SiamRPN');
> ```
> 
> Any hints? Thank you.
me  too    I can not  solve it  ,try  everyehing but fail

**Comment by learnxy** [comment]
@zkloveai 你的问题解决了没

**Comment by foolwood** [comment]
If someone wants to test the OTB results. 
Here is the Step-by-step installation.

```shell
conda create -n siamrpn python=2.7
source activate siamrpn
conda install pytorch torchvision cuda92 -c pytorch
pip install opencv-python

git clone https://github.com/foolwood/DaSiamRPN.git
cd DaSiamRPN/code/data
sh get_otb_data.sh
```
Download model from [Google Drive](https://drive.google.com/open?id=1BtIkp5pB6aqePQGlMb2_Z7bfPy6XEj6H) and save all models (`SiamRPNBIG.model`, `SiamRPNOTB.model` and `SiamRPNVOT.model`) in `DaSiamRPN/code` folder.

```shell
cd DaSiamRPN/code/
python demo.py
python  test_otb.py
python eval_otb.py OTB2015 "Siam*" 0 1
```



If you have any setup problem. We can talk at this issue.

**Comment by xjhjinhui** [comment]
@foolwood 
Could you please tell me why  you don't need pytorch version 0.3 when testing OTB？I tested it with pytorch 0.3, the result is about 0.65, I wonder if the version of pytorch will affect the result and why？
I have noticed that the result of OTB2015  in the paper is more than 80%, how can I reproduce your result?Thanks a lot!

**Comment by sysu-shey** [comment]
I use the correct pytorch version and  pass the original example within the vot-toolkit. However, i meet the same problem as shown before, what can i do?

**Comment by sysu-shey** [comment]
@foolwood Sorry, could you please tell me what can i do to run your code on VOT because i have passed NCC in both python and matlab version?Thanks very much ！TAT

**Comment by xjhjinhui** [comment]
@sysu-shey
I don't know if I can help you, please refer to my summary.
[https://www.cnblogs.com/tay007/p/10656098.html](url)
